### PR TITLE
added str_to_title, str_to_sentence, str_dup, str_length, & str_width

### PR DESCRIPTION
**Pull request by cecoeco**

### CODE REVIEW

**Comment by drizk1** [comment]
This looks great! I'm excited to take a deeper look soon and then merge. Would you mind adding docstrings for each of the new functions first? Let me know if that's something I can help with or give an example of

**Comment by cecoeco** [comment]
Thanks, Daniel. Sounds good. I added docstrings for the new functions.

**Comment by drizk1** [comment]
This looks great thank you. I'll merge this soon. Last thing, if you don't mind, would you be able to update the readme and index.md list of available functions ? Then I'll merge and release ?

I'm happy to add that if you'd prefer as well

**Comment by cecoeco** [comment]
No problems, I added the new functions in the index and README.

**Pull request merged**
